- type: entity
  id: CEBaseStationArrivals
  abstract: true
  components:
    - type: CEStationArrivals

- type: entity
  id: CEBaseStationEconomy
  abstract: true
  components:
  - type: CEStationEconomy
