- type: entity
  id: CEBookBase
  name: book
  description: A hardcover book.
  abstract: true
  categories: [ ForkFiltered ]
  parent: BaseItem
  components:
  - type: Sprite
    sprite: _CE/Objects/Bureaucracy/books.rsi
    layers:
    - state: paper
    - state: cover_base
      color: "#332d27"
      map: [ "cover" ]
    - state: decor_line
      color: "#453f3a"
      map: [ "decor" ]
    - state: icon_plate
      map: [ "icon" ]
    - state: bookmark_short
      map: [ "overlay" ]
  - type: Tag
    tags:
    - Book
  - type: MeleeWeapon
    soundHit:
      collection: Punch
    damage:
      types:
        Blunt: 1
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 1

- type: entity
  id: CEBookWriteableBase
  abstract: true
  parent: CEBookBase
  components:
  - type: Paper
    contentSize: 12000
  - type: ActivatableUI
    key: enum.PaperUiKey.Key
    requiresComplex: false
  - type: UserInterface
    interfaces:
      enum.PaperUiKey.Key:
        type: PaperBoundUserInterface
  - type: PaperVisuals
    backgroundImagePath: "/Textures/Interface/Paper/paper_background_book.svg.96dpi.png"
    backgroundPatchMargin: 23.0, 16.0, 14.0, 15.0
    contentMargin: 20.0, 20.0, 20.0, 20.0

- type: entity
  id: CEGuidebookBase
  abstract: true
  suffix: Guidebook
  parent: CEBookBase
  components:
  - type: GuideHelp
    openOnActivation: true
    guides:
    - SS14

